:url-asciidoc: https://asciidoctor.org/docs/asciidoc-recommended-practices/
:url-vsc: https://code.visualstudio.com/
:url-inkscape: https://inkscape.org/

= HOWTO
Per info su come scrive i documenti asciidoc vedi {url-asciidoc}[AsciiDoc Recommended Practices]

= sviluppo

== ambiente
Non ci sono particolari impostazioni ma normalmente usiamo {url-vsc}[Visual Studio Code], per usare asciidoc va bene l'omonimo plugin: AsciiDoc

Se si usa il client grafico di GitHub e bisogna passare per un proxy: dalla linea di comando `git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`


== diagramma
doc/diagramma_pagine.svg è stato disegnato con {url-inkscape}[Inkscape]


== Configurazione data USBWebServer
per configurare la data bisogna andare nella cartella di impostazioni di USBWebServer "SviluppoWeb\settings",
aprire il file php.ini e cercare il parametro "date.timezone", se esiste, probabilmente è messo come commento,
rimuovere un eventuale ";" davanti il comando e impostare il timezone "Europe/Rome",
se tutto ciò non è presente, basta scrivere "date.timezone = Europe/..."